version: '3.7'
services:
  apache:
    build: ./apache
    container_name: liketoshare_apache
    hostname: liketoshare_apache
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'php:php'
    volumes:
      - './src:/var/www/html'
      - './apache/config:/usr/local/apache2/conf/extra'
  php:
    build: ./php
    container_name: liketoshare_php
    hostname: liketoshare_php
    links:
      - 'mysql:mysql'
    volumes:
      - './src:/var/www/html'
  mysql:
    build: ./mysql
    container_name: liketoshare_mysql
    hostname: liketoshare_mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
