version: '3.3'
services:
  php:
    build: ./php/
    container_name: php_liketoshare
    links:
      - mysql
    ports:
      - "9000:9000"
  apache:
    build: ./apache/
    container_name: apache_liketoshare
    links:
      - php:php
    ports:
      - "8080:8080"
    depends_on:
      - php
  mysql:
    build: ./mysql/
    command: --default-authentification-plugin=mysql_native_password
    restart: always
    container_name: mysql_liketoshare
    ports:
      - "3306:3306"
    environment:
      MYSQL_ENVIRONNEMENT_PASSWORD: root
